services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "3030:8080"
      - "50000:50000"
    volumes:
      - JENKINS_HOME:/var/jenkins_home
  smee:
    build: ./smee
    depends_on:
      - jenkins
volumes:
  JENKINS_HOME:

